name:                RestaurantReservation
version:             0.1.0.0
github:              "githubuser/RestaurantReservation"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thma/RestaurantReservation#readme>

ghc-options:
  - -fplugin=Polysemy.Plugin

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- servant-server
- servant
- time
- wai
- warp
- bytestring
- http-types
- text
- containers
- polysemy
- polysemy-plugin
- errors
- mtl

library:
  source-dirs: src
  ghc-options: -O2 -flate-specialise -fspecialise-aggressively
  default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies

executables:
  RestaurantReservation:
    main:                Main.hs
    source-dirs:         app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -O2 -flate-specialise -fspecialise-aggressively
    dependencies:
    - RestaurantReservation
    default-extensions:
      - DataKinds
      - FlexibleContexts
      - GADTs
      - LambdaCase
      - PolyKinds
      - RankNTypes
      - ScopedTypeVariables
      - TypeApplications
      - TypeOperators
      - TypeFamilies

tests:
  RestaurantReservation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N -O2 -flate-specialise -fspecialise-aggressively
    dependencies:
    - RestaurantReservation
    - hspec
    - QuickCheck
    - hspec-wai
#    - hspec-wai-json
    - wai-extra
    default-extensions:
      - DataKinds
      - FlexibleContexts
      - GADTs
      - LambdaCase
      - PolyKinds
      - RankNTypes
      - ScopedTypeVariables
      - TypeApplications
      - TypeOperators
      - TypeFamilies