name:                RestaurantReservation
version:             0.1.0.0
github:              "githubuser/RestaurantReservation"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/RestaurantReservation#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- servant-server
- servant
- servant-docs
- servant-swagger
- servant-swagger-ui
- servant-swagger-ui-core
- swagger2
- string-conversions
- libiserv
- base-compat-batteries
- time
- wai
- warp
- bytestring
- http-types
- text
- lens
- transformers
- directory
- mtl
- process
- exceptions
- http-media
- time
- containers
- strict

library:
  source-dirs: src

executables:
  RestaurantReservation:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RestaurantReservation

tests:
  RestaurantReservation-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - RestaurantReservation
    - hspec
    - QuickCheck
    - hspec-wai
    - hspec-wai-json